package owner.tests;


import io.qameta.allure.Description;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.WebDriver;
import owner.heplers.WebDriverProvider;

import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {

    private WebDriver driver = new WebDriverProvider().get();

    @Test
    @Description("Autogenerated test")
    @DisplayName("Проверяем текст заголовка вакансии")
    void titleTest() {
        step("Открываем страницу hh", () ->
                open("/vacancy/55442983?from=vacancy_search_list&hhtmFrom=vacancy_search_list&query=qa"));

        step("Заголовок вакансии содержит текст 'Вакансия QA automation / AQA в Москве, работа в компании Системы Распределенного Реестра'", () -> {
            String expectedTitle = "Вакансия QA automation / AQA в Москве, работа в компании Системы Распределенного Реестра";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }
}